### ISSUE TITLE
Distributed workflow

### ISSUE THREAD

**Issue by GabeIsman** [mediapublic/mediapublic#16]
Wanted to jot down some quick thoughts on workflow. The way I see it there are two basic options:
1. Everyone forks mediapublic/mediapublic and works in their own repository. This is the git distributed workflow.
2. Everyone is a contributor to mediapublic/mediapublic and works in branches. Some core group of contributors have commit bits to master. This is the more centralized workflow.
3. Core contributors use workflow 2., people contributing every now and then use 1.

I personally favor 2., because I think it is simpler. If @thequbit is working on some backend feature that hasn't been merged into master yet, I can test it/develop against it simply by merging in his branch. (I can still do this in the distributed workflow but it requires slightly more work). The code on your machine is always up to date after a `git pull`, no need to worry about merging in changes from other remotes.

Thoughts?

**Comment by thequbit** [comment]
I've always done things using flow 1.  This makes me quite partial to it :).   I think this works well when the team is a bit bigger ( usually I play the whole 'never approve your own PR'   game in an attempt to keep code quality as high as possible). 

I'm all for trying something new, however I'm not a huge fan of a bazilion branches for features.  If we go with flow 2 I'd suggest a branch purge after each milestone ( or something like that),  or we make branches that are thequbit-dev,  Gabelsman-dev, etc. 

Was that what you were thinking @Gabelsman?

**Comment by ryansb** [comment]
For core contributors, you can still use a feature branch flow within the repo while also reviewing in pull requests. 
1. Make a branch feature-station-search on the main repo
2. Add commits to branch
3. Open a pull request to master (or develop, as appropriate)
4. Others review the branch and merge it
5. After merging, delete the branch

For non-core developers, the process is identical except that their branch is in a fork instead of the main repo.

For reasons of developer ADD, I try to avoid per-person branching because a single person could be working on a new feature and a couple bugs at the same time, and want them reviewed separately.  

The downside of this flow in high-activity projects where many people may be editing the same code is frequent merges, which aren't awesome.

**Comment by GabeIsman** [comment]
I think we have pretty clearly settled into 2. (or maybe 3, we have yet to have many outside contributor PRs). Closing.
