### ISSUE TITLE
Feature/Page List

### ISSUE THREAD

**Issue by thequbit** [mediapublic/mediapublic#17]
I think we should have a outline of what the site looks like.  Here is my first take at it ... I think we can refine this pretty quickly if everyone gives some input :).  I did this ( kind of ) discussed in #6, but I think it's important to have this actually outlined
- Home
  - This is the landing page for the site.  It should have a brief overview of what it is we're doing here, and simple, easy to understand links to the different parts of the site.
- Listen ( Search/Browse )
  - Search: Google style search bar at the top, and instant-results style results like [fontawesome](http://fortawesome.github.io/Font-Awesome/icons/) search.
  - Here, we would have something like the list of categories/moods/etc. for recordings, and then a user could expand those groupings to see the list of recordings there.
- Recording
  - A single recording page.  Here users can play the recording, get linked back to the station that the recording came from, add the recording to a playlist, and help categorize the recording.
  - This is actually a **big risk** page ... because each station does recordings differently.  An example is how Evan Dawson does his [recordings](http://wxxinews.org/post/connections-summer-book-week-playing-scared) for WXXI.  The player is embedded in the page.
    - Now, looking at the source, you can see that it actually links to an [MP3](http://cpa.ds.npr.org/wxxi/audio/2015/07/Connections-7-20-15Hr2.mp3), but that may not be the case everywhere ...
- Stations Page ( Search/Browse )
  - Search: Similar to Listen, with instant results
  - Browse:  I envision this like the [Craigslist](http://www.craigslist.org/about/sites) browse page, and when you search, stations just drop out of the list ( and states would disappear as there are no more stations in them ).
- Station Page
  - This is the stations landing page where a list of people and recordings will exist ( and tasks? )
- Tasks
  - This is the list-o-tasks that stations have posted.  This is the entry point to midas-like stuff.
- Task
  - Displays a task, and all of it's information.
- People
  - List of people ... unsure how this would work, because we could be talking about 10's of thousands of people ...
- Person
  - A person's personal landing page.  Would have things like links to recordings, their twitter, facebook, instagram, etc.
- How-tos ( Search/Browse )
  - List of how to's.
  - We should have "pinned" howtos as well I think.
- How-to
  - A single howto.
- Blog ( Search/Browse )
  - Normal blog with a list and archive and such.  Tags, etc.
- Blog Post
  - Single blog post.
- About
  - More in-depth about page.

Thoughts/Questions/Concerns?  I think this is a good first-take, but I'm certainly open to ideas/changes and/or if I forgot anything!

@melodykramer maybe it would make sense for you to lead a chat about all of these and we can capture what your vision is?  This is just my first-take ( and some of them are pretty light ... ).  @GabeIsman can you comment on technical challenges you see?

I guess the next step would be to finalize the "what each page does" list, and then do some mock-ups?

**Comment by melodykramer** [comment]
I think we should have a outline of what the site looks like.  Here is my first take at it ... I think we can refine this pretty quickly if everyone gives some input :).  I did this ( kind of ) discussed in #6, but I think it's important to have this actually outlined
- Home
  - This is the landing page for the site.  It should have a brief overview of what it is we're doing here, and simple, easy to understand links to the different parts of the site.

**Yup. I might also include an ability to have a what's new section, so that people who come through the homepage can see what content is new. This could either be auto-generated (preferable) or generated by hand.**
- Listen ( Search/Browse )
  - Search: Google style search bar at the top, and instant-results style results like [fontawesome](http://fortawesome.github.io/Font-Awesome/icons/) search.
  - Here, we would have something like the list of categories/moods/etc. for recordings, and then a user could expand those groupings to see the list of recordings there.

**Questions: How many pieces of audio are displayed and in what order? Most recently tagged, date of publication?**
*\* I might call this section FIND and the next section LISTEN**
- Recording
  - A single recording page.  Here users can play the recording, get linked back to the station that the recording came from, add the recording to a playlist, and help categorize the recording.
  - This is actually a **big risk** page ... because each station does recordings differently.  An example is how Evan Dawson does his [recordings](http://wxxinews.org/post/connections-summer-book-week-playing-scared) for WXXI.  The player is embedded in the page.
    - Now, looking at the source, you can see that it actually links to an [MP3](http://cpa.ds.npr.org/wxxi/audio/2015/07/Connections-7-20-15Hr2.mp3), but that may not be the case everywhere ...

*\* I would call this page LISTEN. For an MVP and because sites aren't standardized, what if we only do it for stations that are part of NPR Digital Services (which means the audio would be standardized...) - there are enough stations that fit that requirement. For pages that aren't, perhaps we don't find the audio but simply bring in the link to the page containing the audio?**
- Stations Page ( Search/Browse )
  - Search: Similar to Listen, with instant results
  - Browse:  I envision this like the [Craigslist](http://www.craigslist.org/about/sites) browse page, and when you search, stations just drop out of the list ( and states would disappear as there are no more stations in them ).

**Yup.**
- Station Page
  - This is the stations landing page where a list of people and recordings will exist ( and tasks? )

*\* People, recordings, and ways to help the station**
- Tasks
  - This is the list-o-tasks that stations have posted.  This is the entry point to midas-like stuff.

**Yup**
- Task
  - Displays a task, and all of it's information.

**Yup.**
- People
  - List of people ... unsure how this would work, because we could be talking about 10's of thousands of people ...

**8,000 total, not all will add.**
- Person
  - A person's personal landing page.  Would have things like links to recordings, their twitter, facebook, instagram, etc.

**Yes**
- How-tos ( Search/Browse )
  - List of how to's.
  - We should have "pinned" howtos as well I think.

**Yes, also maybe ability to surface on main page**
- How-to
  - A single howto.

**Yes.**
- Blog ( Search/Browse )
  - Normal blog with a list and archive and such.  Tags, etc.
- Blog Post
  - Single blog post.
- About / How to Contribute 
  - More in-depth about page.

*_How to get involved with the project / who we are / what's next *_

Thoughts/Questions/Concerns?  I think this is a good first-take, but I'm certainly open to ideas/changes and/or if I forgot anything!

@melodykramer maybe it would make sense for you to lead a chat about all of these and we can capture what your vision is?  This is just my first-take ( and some of them are pretty light ... ).  @GabeIsman can you comment on technical challenges you see?

I guess the next step would be to finalize the "what each page does" list, and then do some mock-ups?

**Comment by nkkl** [comment]
Feature request: can someone make a visual (sketch) of this? That would
cause me to grok it about a thousand times better. :)

@nkkl
323.205.6533

**Comment by thequbit** [comment]
/me raises hand.

@nkkl I'll put together a little visual of sorts this evening with @melodykramer comments, as well as updating my issue contents with her comments.

**Comment by thequbit** [comment]
I've uploaded mock-ups here:

http://mediapublic.github.io/mockups/

Don't forget to click on one of the stations ( they all go to a bogus page ).

I've added the notes above to each page.

**Comment by GabeIsman** [comment]
### A wild Negative Nancy appears

Maybe this is the wrong place to bring up these concerns but I continue to have nagging doubts that we really haven't yet focused in on what exactly we are trying to do, and what assumptions we are testing.

I see three distinct problems that we are trying to solve.
1. The public has no way of contributing to a public radio station in non-monetary
   ways.
2. Public radio stations don't communicate very well with each other.
3. It's hard to find the excellent content that public radio stations have produced in the past.

I think we could take any _one_ of these three problems and build something really awesome to tackle it over the next six months. I have this terrible feeling that if we try to take on all three we're going to end up sort of half-assing all of them.

The ways we've talked about attempting to solve each of these problems are respectively (forgive my simplification):
1. Adapt Midas to work really well for public radio stations. Integrate it into their CRM's so memberships can be awarded, promote a culture of involving the public within radio stations, maybe we are also making Hive easily deployable by a station on their own archives.
2. Create a sort of social network for public radio, where each station has a page, each journalist/producer/coder/etc has a page, they can all share information with each other through how-to's and open-source projects.
3. Create a page where archival content can be resurfaced, where people can make and share playlists, where people can add audio (scraped by us?), where audio will be surfaced in interesting using interesting tags, we would also build the tagging system?

Each of these projects, frankly, sounds like an ambitious one for a small handful of people who all have other jobs to tackle in six months. Trying to do them all at once sounds impossible.

I propose that we think a little harder about which of these three projects is most important, most feasible, and most effectively tests our assumptions. I propose that we pick one, and build it, launch it, see what happens, and then decide what to do next.

We can always keep building iteratively. If we adapt Midas and find that what's really lacking is the communication between stations, we build that next. If every station wants us to make crowd-sourced archival work easier, we build out a Hive integration next. 

I hope this doesn't come off as overly critical or too harsh, I just keep having this bad feeling that we haven't really honed in on what it is that we really want to get out of this thing. I would much rather focus on something and build something small really well that can become part of something larger down the line, than build something big and not very developed.

My two cents. I look forward to hearing everyone else's. Am I crazy? Is this all actually easier than I am imagining?

**Comment by nkkl** [comment]
I think that I can add value here because PM and designer, but I would need
us to commit to a meeting where we could see and hear each other in team
time for at least an hour probably 2 or 3. Your concerns are valid and
should be addressed. I don't think they are showstoppers, but we may need
to scope down to something really crisp for our MVP and then build up from
there.

@nkkl
323.205.6533

**Comment by GabeIsman** [comment]
I am definitely pro face-to-face team conversations!

**Comment by nkkl** [comment]
Woo!

Obnoxiously, I am traveling tomorrow night through Monday evening and do
not intend to bring a computer. However, I will make time after I get back.

@nkkl
323.205.6533

**Comment by melodykramer** [comment]
@thequbit @nkkl @GabeIsman How about Tuesday evening?

**Comment by ryansb** [comment]
Are any notes from this meeting around? I'd love to hear what kind of user stories/goals you came up with.

**Comment by thequbit** [comment]
@ryansb we didn't do a good job with taking written notes ( I did not at least ).  I think @melodykramer may have??

We decided that we wanted to something like solution 2 above ...

> 1. Create a sort of social network for public radio, where each station has a page, each journalist/producer/coder/etc has a page, they can all share information with each other through how-to's and open-source projects.

... with a hope to solve problem 2 and 3 above ...

> 2.Public radio stations don't communicate very well with each other.
> 3. It's hard to find the excellent content that public radio stations have produced in the past.

I think, at least, that is what I got out of it.  We're having another meeting on Tuesday to refine this, I believe.

**Comment by thequbit** [comment]
@ryansb I knew I posted about this somewhere, I just found it here:

https://github.com/mediapublic/mediapublic/issues/24#issuecomment-123923702

That is kind of the thought/flow.  @melodykramer was awesome and did take notes ( knew she did, ha ).  They are here:

https://github.com/mediapublic/mediapublic/wiki/Notes-for-Station-Page-Experience.

**Comment by GabeIsman** [comment]
While the discussion in this issue is great, I think it has been superseded by the more current https://github.com/mediapublic/mediapublic/issues/78.

**Comment by thequbit** [comment]
:+1:
