### ISSUE TITLE
A Public Intranet for Public Media (newsletter feedback)

### ISSUE THREAD

**Issue by melodykramer** [mediapublic/mediapublic#26]
Link to newsletter: http://tinyletter.com/mediapublic/letters/a-public-intranet-for-public-media

So what questions do you have?

**Comment by reblavoie** [comment]
A lot pubradio stations are on the Core Publisher platform. While some of us on the digital side have adopted cloud-based tools, code, hacked iFrames, redirects, and other creative workarounds for CP's limitations, there isn't a central wiki for this stuff. Is there some potential with this project to create such a thing, like a repository that's searchable in which we can share our tricks and favorite tools? While it's nice to be able to Facebook IM a colleague and ask, 'how did you do that?', it would be nice to accumulate a library of sorts.

**Comment by melodykramer** [comment]
Yes! I keep seeing questions on the many public radio social platforms that ask for these things! It would be great to have them in once place, particularly if it's open and easily searchable. cc: @thequbit

**Comment by thequbit** [comment]
Absolutely.  I think we should keep this specific question in mind when designing the /Learn section.  I really do like the wiki format, however it is very easy to have it fall apart into worthlessness ( read: it takes someone who really knows what they are doing to make sure the wiki doesn't become a complete mess ).

@reblavoie thanks for passing this along!

**Comment by ryansb** [comment]
@reblavoie Are you looking for a searchable set of tutorials on doing X with Core Publisher (or other pubradio things), or are you thinking more along the lines of a wiki page for each separate tool?

**Comment by melodykramer** [comment]
@ryansb I'm envisioning more of a Reddit/Quora style Q/A or place to collect material (radio stories featuring kids, radio stories featuring long-form journalism, etc.) that people frequently use in presentations.

**Comment by katemyers** [comment]
Is there some possibility of cross-publishing or at least linking to existing resources? One advantage to a Wikipedia versus a Quora when it comes to answers is that you're naturally linking out to places where it has been answered (and doesnt cause you to have to replicate them on your intranet).

For example: There are many existing resources on Tumblr strategy for instance: http://digitalservices.npr.org/term/tumblr
http://socialmediadesk.tumblr.com/post/91982994861/social-sandbox-tips-for-tumblr
http://socialmediadesk.tumblr.com/post/67579486986/trying-out-tumblr-on-the-road-with-npr
https://github.com/nprapps/tumble
https://github.com/nprapps/pytumblr
https://source.opennews.org/en-US/articles/how-nprs-apps-team-covered-elections/

All of those to me make sense to be cited as part of a wikipedia style discussion on tumblr strategy, rather than thinking of having to recreate them ala Reddit or Quora. Just a thought.

**Comment by melodykramer** [comment]
I think most of what we're doing is going to be linking outwards - and I think Quora, Wikipedia, Ask Metafilter - etc. do that a great deal. I think we're thinking about how to structure this - a wiki is very different than git - not in terms of outcomes, but how changes are integrated into the final piece.

**Comment by melodykramer** [comment]
I actually really like this: https://github.com/18F/hub/ - it allows for different levels of access, it's easy to use, and we use it like a wiki - but it requires two eyeballs before changes are made.

**Comment by GabeIsman** [comment]
Closing this feedback issue. Thanks for the great thoughts everyone! I think we've pretty well incorporated these ideas into the current understanding of the goal.
