### ISSUE TITLE
Design sketches for Media Public

### ISSUE THREAD

**Issue by melodykramer** [mediapublic/mediapublic#45]
https://docs.google.com/document/d/1mw5T2WK-HfKCWKi5b0X_p-j4L_0iHdKMkxHIMxCYevI/edit?usp=sharing

**Comment by melodykramer** [comment]
Draft of Newsletter 2: Sunday
1. What Tim has done
2. Google Hangout next week to work in real time on issues (we'll need some issues for the audience to work on)
3. What Nikki and Mel have been up to
4. What Isaac is working on
5. Meet Ryan
6. We have a designer for a logo! He's going to work in public.

**Comment by nkkl** [comment]
What action items are needed for this?

**Comment by thequbit** [comment]
I would say that #79, #80, #81, #82, #83, #84, #85, #86, and #103 are the action items for this issue.  At the same time, I think this probably should have been a wiki entry rather than an issue ( although we really don't have a solid flow for documenting "we did some talking off-line and made these decisions" kind of stuff.

There are wiki entries for meeting notes already.  I think this should probably be moved there.

**Comment by thequbit** [comment]
Made a wiki page.  Closing this issue.

Ref: https://github.com/mediapublic/mediapublic/wiki/Melody-and-Nikki-convo-on-site-architecture.
