### ISSUE TITLE
CORS settings do not apply to errors and framework-level responses

### ISSUE THREAD

**Issue by GabeIsman** [mediapublic/mediapublic#58]
Whenever I get an error response (e.g. 500, 415) I end up with a CORS error. Would be nice if we could figure out a way to apply CORS headers to all responses.

**Comment by thequbit** [comment]
I suspect this is happening because the cors policy isn't being applied to the response unless it's 2xx.  I'm sure @ryansb has some thoughts, but I think we can back-burner this until we get the rather large PR from ryan figured out with all of the twitter auth stuff.  That okay with you @GabeIsman ?

**Comment by GabeIsman** [comment]
@thequbit Yep. No rush on this.

**Comment by ryansb** [comment]
Ah, I see. I'm not sure how to apply it to everything automatically, but I can apply those to the error/forbidden views.

**Comment by GabeIsman** [comment]
This is fixed.
