### ISSUE TITLE
Model validations too strict

### ISSUE THREAD

**Issue by GabeIsman** [mediapublic/mediapublic#61]
When I POST to /organizations with some fairly reasonable data I get this response:

```
{
    "errors": [
        {
            "location": "body",
            "name": "address_1",
            "description": "Required"
        },
        {
            "location": "body",
            "name": "fax",
            "description": "Required"
        },
        {
            "location": "body",
            "name": "secondary_website",
            "description": "Required"
        }
    ],
    "status": "error"
}
```

An organization doesn't necessarily have two websites, they might not even have one! I think we should relax our standards about which fields can be nullable (probably generally, but these three for sure).

**Comment by GabeIsman** [comment]
BTW, wanted to clarify that the data I posted had these fields as empty strings.

**Comment by ryansb** [comment]
Ok, that's great feedback. 

For reference, those validations are derived from what fields we have required in the database. You can fix these in server/mediapublic/models.py by making the field optional. 

Since nobody uses fax machines, you could head [here](https://github.com/mediapublic/mediapublic/blob/develop/server/mediapublic/models.py#L372) and change `fax = Column(UnicodeText, nullable=False)` to `fax = Column(UnicodeText)` since the default is to make a field optional.

**Comment by ryansb** [comment]
Also, as I'm sure you know, since you're the only consumer of the API at the moment we can make whatever sweeping changes you want.

**Comment by GabeIsman** [comment]
Closed by https://github.com/mediapublic/mediapublic/pull/95
